import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./provides";
import Header from "@/components/Header/Header";
import { SelectedOptionProvider } from "./context/MyContext";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer/Footer";
import { CartProvider } from "./context/CartContext";



export const metadata: Metadata = {
  title: "shop",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode}) {



  return (
    <html lang="en">
      <body>
        <CartProvider>
          <SelectedOptionProvider>
            <Providers>
              <Toaster position="top-center" />
              <Header  />
              <div className="py-32 bg-gray-100 min-h-[600px]">
                {children}
              </div>
              <Footer />
            </Providers>
          </SelectedOptionProvider>
        </CartProvider>
      </body>
    </html>
  );
}
