import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./provides";
import Header from "@/components/Header/Header";
import { SelectedOptionProvider } from "./context/MyContext";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer/Footer";

export const metadata: Metadata = {
  title: "shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <SelectedOptionProvider>
          <Providers>
            <Header />
            <div className="mt-32 mb-20">
            <Toaster position="top-center" />
              {children}
              </div>
              <Footer/>
          </Providers>
        </SelectedOptionProvider>
      </body>
    </html>
  );
}
